name: HyzardEssentials
version: 1.0
main: me.zbrunooow.hyzardessentials.Core
load: POSTWORLD
authors: [ zBrunooow, lHawk_ ]
depend: [Vault]
softdepend: [PlaceholderAPI, H_Economy, HawkCore]
description: Rede Hyzard - Core FullPvP

commands:

  craft:
#   permission: hyzardcore.craft

  bigorna:
    aliases: [anvil]
#   permission: hyzardcore.bigorna

  echest:
    aliases: [ec, enderchest]
#   permission: hyzardcore.echest

  clear:
#   permission: hyzardcore.clear

  hat:
    aliases: [chapeu]
#   permission: hyzardcore.hat

  alerta:
    aliases: [title]
#   permission: hyzardcore.alerta

  aviso:
    aliases: [broadcast, bc]
#   permission: hyzardcore.aviso

  gamemode:
    aliases: [gm]
#   permission: hyzardcore.gamemode

  ping:

  divulgar:
#   permission: hyzardcore.divulgar

  setspawn:
    aliases: [setarspawn]
#   permission: hyzardcore.setspawn

  setwarp:
    aliases: [setarwarp]
#   permission: hyzardcore.setspawn

  perfil:

  renomear:
    aliases: [rename]
#   permission: hyzardcore.renomear

  invsee:
    aliases: [inventario]
#   permission: hyzardcore.invsee

  spawn:
#   permission: hyzardcore.spawnvip (ou nenhuma para ir ao spawn normal)

  warp:
    aliases: [warps]
#   permission: hyzardcore.warp.nomewarp

  deletarwarp:
    aliases: [delwarp]
#   permission: hyzardcore.delwarp

  heal:
    aliases: [curar, cura]
#   permission: hyzardcore.heal (listar warps no chat)

  feed:
    aliases: [fome]
#   permission: hyzardcore.feed / hyzardcore.feed.outros

  hyzardessentials:
    aliases: [hyzardcore, hess, hyzard]
#   permission: hyzardcore.admin

  back:
    aliases: [voltar]
#   permission: hyzardcore.back

  clearchat:
    aliases: [cc, limparchat, chatclear]
#   permission: hyzardcore.clearchat

  online:

  head:
    aliases: [skull]
#   permission: hyzardcore.head

  luz:
#   permission: hyzardcore.luz

  fly:
    aliases: [voar]
#   permission: hyzardcore.fly
#   permission: hyzardcore.fly.outros

  god:
    aliases: [deus]
#   permission: hyzardcore.god

  give:
#   permission: hyzardcore.give

  sudo:
#   permission: hyzardcore.sudo

  enchant:
    aliases: [encantar]
#   permission: hyzardcore.enchant

  lixo:
    aliases: [lixeira, trash]

  cores:

  teleport:
    aliases: [tp]
#   permission: hyzardcore.teleport

  tpall:
    aliases: [teleportall]
#   permission: hyzardcore.tpall

  tphere:
    aliases: [teleporthere, puxar]
#   permission: hyzardcore.tphere

  derreter:
#   permission: hyzardcore.derreter

  compactar:
#   permission: hyzardcore.compactar

  kill:
    aliases: [matar]
#   permission: hyzardcore.kill
#   permission: hyzardcore.kill.outros

  potion:
    aliases: [pocao]
#   permission: hyzardcore.potion

  lore:
#   permission: hyzardcore.lore

  tpa:
#   permission: hyzardcore.tpa
  tpaccept:
#   permission: hyzardcore.tpaccept
  tpcancel:
#   permission: hyzardcore.tpcancel
  tpdeny:
#   permission: hyzardcore.tpdeny

  playtime:

  desencantar:
#   permission: hyzardcore.desencantar

  kit:
    aliases: [kits]
  #   permission: hyzardcore.kit.nome
  criarkit:
#   permission: hyzardcore.criarkit
  deletarkit:
    aliases: [delkit]
#   permission: hyzardcore.delkit

  speed:
    aliases: [velocidade]
#   permission: hyzardcore.speed

  flyspeed:
#   permission: hyzardcore.flyspeed

  sethome:
    aliases: [setarhome]
#   permission: hyzardcore.sethome
#   permission: hyzardcore.homes.NUMERO (ex: hyzardcore.homes.5) - O PADRÃO É 2

  home:
    aliases: [homes]
#   permission: hyzardcore.home

  delhome:
    aliases: [deletarhome]
#   permission: hyzardcore.home

  viciado:

  givecaixakill:

  ajuda:
    aliases: [ticket]
  verticket:
    aliases: [verajuda]