name: HyzardEssentials
version: 1.0
main: me.zbrunooow.hyzardessentials.Core
load: POSTWORLD
authors: [ zBrunooow, lHawk_ ]
softdepend: [PlaceholderAPI]
description: Rede Hyzard - Core FullPvP
commands:
  craft:
#   permission: hyzardcore.craft

  bigorna:
    aliases: [anvil]
#   permission: hyzardcore.bigorna

  echest:
    aliases: [ec, enderchest]
#   permission: hyzardcore.echest

  clear:
#   permission: hyzardcore.clear

  hat:
    aliases: [chapeu]
#   permission: hyzardcore.hat

  vanish:
    aliases: [v]
#   permission: hyzardcore.vanish

  alerta:
    aliases: [title]
#   permission: hyzardcore.alerta

  aviso:
    aliases: [broadcast, bc]
#   permission: hyzardcore.aviso

  gamemode:
    aliases: [gm]
#   permission: hyzardcore.gamemode

  ping:

  divulgar:
#   permission: hyzardcore.divulgar

  setspawn:
    aliases: [setarspawn]
#   permission: hyzardcore.setspawn

  setwarp:
    aliases: [setarwarp]
#   permission: hyzardcore.setspawn

  perfil:

  renomear:
    aliases: [rename]
#   permission: hyzardcore.renomear

  invsee:
    aliases: [inventario]
#   permission: hyzardcore.invsee

  spawn:
#   permission: hyzardcore.spawnvip (ou nenhuma para ir ao spawn normal)

  warp:
#   permission: hyzardcore.warp.nomewarp
#   permission: hyzardcore.warps (listar warps no chat)

  heal:
    aliases: [curar, cura]
#   permission: hyzardcore.heal (listar warps no chat)

  feed:
    aliases: [feed]
#   permission: hyzardcore.feed / hyzardcore.feed.outros

  hyzardessentials:
    aliases: [hyzardcore, hess, hyzard]
#   permission: hyzardcore.admin

  info:
    aliases: [discord, dc, site, servidor]

  back:
#   permission: hyzardcore.back

  clearchat:
    aliases: [cc, limparchat, chatclear]
#   permission: hyzardcore.clearchat

  online:

  head:
    aliases: [skull]
#   permission: hyzardcore.head

  luz:
#   permission: hyzardcore.luz

  fly:
#   permission: hyzardcore.fly
#   permission: hyzardcore.fly.outros

  god:
#   permission: hyzardcore.god

  give:
#   permission: hyzardcore.give

  giveold:
