name: HyzardCore
version: 1.0
main: me.zbrunooow.HyzardCore.Core
load: POSTWORLD
authors: [ zBrunooow ]
description: Rede Hyzard - Core FullPvP
commands:
  craft:
    permission: hyzardcore.craft
  bigorna:
    permission: hyzardcore.bigorna
  echest:
    aliases: [ec, enderchest]
    permission: hyzardcore.echest
  clear:
    permission: hyzardcore.clear


