name: HyzardCore
version: 1.0
main: me.zbrunooow.HyzardCore.Core
load: POSTWORLD
authors: [ zBrunooow ]
description: Rede Hyzard - Core FullPvP
commands:
  craft:
#   permission: hyzardcore.craft
  bigorna:
    aliases: [anvil]
#   permission: hyzardcore.bigorna
  echest:
    aliases: [ec, enderchest]
#   permission: hyzardcore.echest
  clear:
#   permission: hyzardcore.clear
  hat:
    aliases: [chapeu]
#   permission: hyzardcore.hat
  vanish:
    aliases: [v]
#   permission: hyzardcore.vanish
  alerta:
    aliases: [title]
#   permission: hyzardcore.alerta
  aviso:
    aliases: [broadcast, bc]
#   permission: hyzardcore.aviso
  gamemode:
    aliases: [gm]
#   permission: hyzardcore.gamemode
  ping:
  divulgar:
#   permission: hyzardcore.divulgar
  perfil:


